//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopingStore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Order()
        {
            this.Tbl_OrderDetail = new HashSet<Tbl_OrderDetail>();
        }
    
        public int OrderID { get; set; }
        public int UserID { get; set; }
        public int PaymentID { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public string CardNumber { get; set; }
        public string NameOnCard { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_OrderDetail> Tbl_OrderDetail { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
        public virtual Tbl_Payment Tbl_Payment { get; set; }
    }
}
